[package]
name = "seikinosusume"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Kyure-A/seikinosusume"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
og_image_writer = "0.11.0"
wasm-bindgen = "0.2.87"
